baseURL       = "http://aidos.group/"
languageCode  = "en-us"
title         = "AIDOS Lab"
theme         = "brevis"
enableGitInfo = true

[params]
  description = "Website of the AIDOS Lab, an international lab of researchers interested in geometry, topology, and machine learning."
  googleTagID = "G-Z7H79RP4BR"
  ogImage     = "logo_with_byline.png"

ignoreFiles = ['publications.md$']

[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.goldmark.extensions]
    typographer = true

  [markup.tableOfContents]
    endLevel = 3

[[menu.main]]
  name    = "Welcome"
  pageRef = "/"
  weight  = -150

[[menu.main]]
  name    = "Guide"
  url     = "/guide"
  weight  = -100

[[menu.main]]
  name    = "People"
  pageRef = "/people"
  weight  = -90

[[menu.main]]
  name    = "Research"
  pageRef = "/research"
  weight  = -80

[[menu.main]]
  name    = "Blog"
  pageRef = "/blog"
  weight  = -80

[[menu.main]]
  name    = "Theses"
  pageRef = "/theses"
  weight  = -80

[[menu.main]]
  name    = "Get In Touch"
  pageRef = "/contact"
  weight  = -70

[[menu.main]]
  name   = "Wiki"
  url    = "/wiki/"
  weight = -70

[params.footer.logos]
  text = """
  <a href="https://www.unifr.ch"><img src="/signet_unifr.svg" height="32" alt="University of Fribourg"></a>
  <a href="https://www.helmholtz-muenchen.de/en"><img src="/logo_helmholtz_munich.svg" height="32" alt="Helmholtz Munich" style="padding-left:16px"></a>
  <a href="https://en.wikipedia.org/wiki/Rainbow_flag_(LGBTQ)"><img src="/progress_flag.svg" height="32" style="padding-left:16px; padding-right:16px" alt="Pride flag"></a>
"""

[params.footer.license]
  text = """
All external logos are copyrighted and may not be used without
express permission. The remainder of the content, if not specified otherwise,
has been created by <a href="https://bastian.rieck.me">Bastian Rieck</a>
and is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
"""
